theme: jekyll-theme-slate
title: Welcome to the Octocat’s homepage!
description: ookmark this to keep an eye on my project updates.
I have goodwill for all but I am allied to none. A hearty welcome to all to my website  
